version: '3.8'

services:
  web:
    image: php:apache  # Образ с PHP и Apache
    volumes:
      - ./:/var/www/html/
    ports:
      - "80:80"
    depends_on:
      - db
      - ioncube
    restart: always

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: opencart
      MYSQL_USER: opencart
      MYSQL_PASSWORD: opencart
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  ioncube:
    image: atsu666/ioncube:7.0
    volumes:
      - ./:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    links:
      - db
    environment:
      - VIRTUAL_HOST=example.dev
      - APACHE_DOCUMENT_ROOT=/var/www/html 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: always

volumes:
  db_data:
